name: mudlet-linux # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '4.17.2' # just for humans, typically '1.2+git' or '1.3.2'
summary:  A cross-platform, open source, and super fast MUD client with scripting in Lua
description: |
   Mudlet is a platform for gaming and enhancing game-play primarily with MUDs.  Mudlet provides a toolkit and supports a wide variety of protocols for players and creators to tailor an immersive game-playing experience. MUD creators can use Mudlet to add visual flair or build features into their text games. MUD players can utilize the Mudlet toolkit to script and automate parts of their gameplay or add their own visual customization for game data. Outside the realm of MUD games, Mudlet has even been used to provide automation and features in 3D games which support in-game chat and a Telnet or similar server-console protocols.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
icon:  mudlet_icon.png
title: Mudlet

apps:
  mudlet:
    command: mudlet
parts:
  mudlet:
    # See 'snapcraft plugins'
    plugin: dump
    source: .
#    build-packages: [default-jre]
#    stage-packages: [default-jre]
    organize:
      mudlet: build/
      mudlet.1: man/man1/

architectures:
  - build-on: amd64

